### ISSUE TITLE
大佬请问数据集咋搞

### ISSUE THREAD

**Issue by nathan123770** [jun-wei-zeng/movie_recommendation_system_server#1]

**Comment by jun-wei-zeng** [comment]
你好，数据集是通过爬虫得到的，爬的是豆瓣平台的数据，爬虫项目暂时没有开源，有需要的话后续有空我整理一下再开源。

**Comment by nathan123770** [comment]
大佬接私活吗冒昧问一下

**Comment by jun-wei-zeng** [comment]
不好意思，最近比较忙，不接私活。

**Comment by IstarsGandalf** [comment]
大佬请问可以给一下数据集sql吗，拿来学习一下，不然前台都是空的

**Comment by jun-wei-zeng** [comment]
@IstarsGandalf, 之前数据集我是存储在某云服务器（文本数据在数据库中，电影海报等图像在OSS中）上的，现在已经过期自动注销了，我当时并没有备份，所以数据集没有保存下来。但是爬虫的代码还在，我晚点开源一下。

**Comment by jun-wei-zeng** [comment]
爬虫仓库已开源，有需要数据集的请自己爬虫一下，仓库地址：[douban_movie_spider_mrs](https://github.com/jun-wei-zeng/douban_movie_spider_mrs)
